# SITE SETTINGS
homepage_title: ShiftVision
homepage_headline: "Joachim den Hertog"
homepage_description: "Entrepeneur at ReSnap and ShiftVision"
# META
site_title: ShiftVision
site_author: gjdenhertog
site_description: "Joachim den Hertog - Entrepeneur at ReSnap and ShiftVision."
site_keywords: 'shiftvision, javascript, nodejs, gjdenhertog, blog'
# CUSTOMIZE 
color_theme: nominal # only one theme right now, sry
# SOCIAL
social_twitter: "https://twitter.com/gjdenhertog"
social_instagram: "https://www.instagram.com/gjdenhertog/"
social_github: "https://github.com/gjdenhertog"
social_linkedin: "https://www.linkedin.com/in/gjdenhertog"


# JEKYLL - Misc
#
# Web Server Settings
url: "gjdenhertog.github.io"
# url: "http://localhost:4000"
# url: "http://estrattonbailey.com/Nominal" # Change this to match your domain name

# Gems
gems: [jekyll-paginate]
# Hide these files from jekyll build process.
exclude: [README.md]
# Blog pagination settings.
paginate: 8
paginate_path: words/page-:num
# Permalink setting for posts.
permalink: words/:title
permalink_base: words/
# Build settings
markdown: redcarpet
# Sass Settings
sass:
  sass_dir: _scss
  style: :compact